fix(ci): retry generator jobs
Problem:
docgen fails if gen-annotations pushes before it:

    [master c2804a4] docs: update configs.md skip-checks: true
     2 files changed, 24 insertions(+), 20 deletions(-)
    To https://github.com/neovim/nvim-lspconfig
     ! [rejected]        master -> master (fetch first)
    error: failed to push some refs to 'https://github.com/neovim/nvim-lspconfig'
    hint: Updates were rejected because the remote contains work that you do not
    hint: have locally. This is usually caused by another repository pushing to

Solution:
If push fails, rebase and retry. The two workflows touch disjoint files
so the rebase should alway resolve.